POST  http://localhost:8080/create-buyer
content-Type: application/json

{
    "NamaPerusahaan": "tesabc",
	"WebsitePerusahaan": "tesabc",  
	"NomorTelepon": "+2",       
	"Negara": "tesabc",             
	"EmailPerusahaan": "tesabc",
	"KomoditasPerusahaan": "tesabc"
}