POST  http://localhost:8080/create-buyer
content-Type: application/json

{
    "NamaPerusahaan": "tes",
	"WebsitePerusahaan": "tes",  
	"NomorTelepon": "tes",       
	"Negara": "tes",             
	"EmailPerusahaan": "tes"   
}